In [72]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [ ]:
df = sns.load_dataset("iris")
df.to_csv('./iris.csv')

In [74]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [75]:
X = df.drop('species',axis=1)
y = df['species']

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [77]:
model_knn = KNeighborsClassifier()
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [78]:
model_knn.score(X_test,y_test)

1.0

In [79]:
model_svc = SVC(gamma='auto')
model_svc.fit(X_train,y_train)

SVC(gamma='auto')

In [80]:
model_svc.score(X_test,y_test)

1.0

In [81]:
classifier = GridSearchCV(model_svc,param_grid={
    'C': [1,10,20,30],
    'kernel': ['rbf','linear'],
    'gamma': ['auto','scale']
},cv=5,return_train_score=False)
classifier

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear']})

In [82]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear']})

In [83]:
result = pd.DataFrame(classifier.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009031,0.003631,0.011623,0.011679,1,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.006337,0.000998,0.004700,0.000844,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.008096,0.002145,0.007910,0.002896,1,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,0.966667,0.966667,0.933333,1.0,0.966667,0.021082,11
3,0.005530,0.000923,0.004174,0.000484,1,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
4,0.006997,0.001967,0.005710,0.000714,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.006810,0.000954,0.005942,0.000911,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,7
6,0.004404,0.000719,0.002847,0.000942,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
7,0.005485,0.001246,0.003664,0.000607,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,7
8,0.004227,0.000414,0.004387,0.000991,20,auto,rbf,"{'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,10
9,0.004280,0.001402,0.003467,0.001437,20,auto,linear,"{'C': 20, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,11
10,0.004982,0.000802,0.003168,0.000143,20,scale,rbf,"{'C': 20, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
11,0.004581,0.000706,0.004218,0.000801,20,scale,linear,"{'C': 20, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,11
12,0.005026,0.000913,0.003812,0.000417,30,auto,rbf,"{'C': 30, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,14
13,0.005665,0.001106,0.004407,0.000355,30,auto,linear,"{'C': 30, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,14
14,0.006631,0.000772,0.004827,0.000936,30,scale,rbf,"{'C': 30, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
15,0.005563,0.000500,0.004417,0.000319,30,scale,linear,"{'C': 30, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,14

In [84]:
classifier = GridSearchCV(model_knn,param_grid={
    'n_neighbors': [1,3,5,7,9,11,13,15,17,19,21,23,25],
    'weights': ['uniform','distance'],
    'algorithm': ['auto','ball_tree','kd_tree','brute']
},cv=5,return_train_score=False)
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21,
                                         23, 25],
                         'weights': ['uniform', 'distance']})

In [85]:
result = pd.DataFrame(classifier.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008523,0.003037,0.008834,0.002044,auto,1,uniform,"{'algorithm': 'auto', 'n_neighbors': 1, 'weigh...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,89
1,0.006962,0.001726,0.006765,0.001031,auto,1,distance,"{'algorithm': 'auto', 'n_neighbors': 1, 'weigh...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,89
2,0.007574,0.000494,0.008038,0.000905,auto,3,uniform,"{'algorithm': 'auto', 'n_neighbors': 3, 'weigh...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,57
3,0.005852,0.000919,0.005581,0.001174,auto,3,distance,"{'algorithm': 'auto', 'n_neighbors': 3, 'weigh...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,57
4,0.005838,0.001877,0.009208,0.001474,auto,5,uniform,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,0.002965,0.000154,0.003359,0.000366,brute,21,distance,"{'algorithm': 'brute', 'n_neighbors': 21, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,26
100,0.002953,0.000145,0.003899,0.000143,brute,23,uniform,"{'algorithm': 'brute', 'n_neighbors': 23, 'wei...",0.933333,1.000000,0.933333,0.933333,1.0,0.960000,0.032660,89
101,0.003621,0.000688,0.004328,0.000557,brute,23,distance,"{'algorithm': 'brute', 'n_neighbors': 23, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,5
102,0.004408,0.000753,0.004923,0.001109,brute,25,uniform,"{'algorithm': 'brute', 'n_neighbors': 25, 'wei...",0.933333,0.966667,0.933333,0.966667,1.0,0.960000,0.024944,89
103,0.003008,0.000758,0.003068,0.000152,brute,25,distance,"{'algorithm': 'brute', 'n_neighbors': 25, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,57